pub enum Section {
    App,
    Article,
    Bug,
    Blog,
    Club,
    Contest,
    Concept,
    Event,
    Game,
    Idea,
    Initiative,
    Jam,
    Mod,
    Model,
    Member,
    News,
    Poll,
    Project,
    Question,
    Review,
    Request,
    Script,
    Sound,
    Spray,
    Studio,
    Thread,
    Tool,
    Tutorial,
    Wiki,
    Wip,
}

impl Section {
    pub fn as_str(&self) -> &str {
        match self {
            Section::App => "App",
            Section::Article => "Article",
            Section::Bug => "Bug",
            Section::Blog => "Blog",
            Section::Club => "Club",
            Section::Contest => "Contest",
            Section::Concept => "Concept",
            Section::Event => "Event",
            Section::Game => "Game",
            Section::Idea => "Idea",
            Section::Initiative => "Initiative",
            Section::Jam => "Jam",
            Section::Mod => "Mod",
            Section::Model => "Model",
            Section::Member => "Member",
            Section::News => "News",
            Section::Poll => "Poll",
            Section::Project => "Project",
            Section::Question => "Question",
            Section::Review => "Review",
            Section::Request => "Request",
            Section::Script => "Script",
            Section::Sound => "Sound",
            Section::Spray => "Spray",
            Section::Studio => "Studio",
            Section::Thread => "Thread",
            Section::Tool => "Tool",
            Section::Tutorial => "Tutorial",
            Section::Wiki => "Wiki",
            Section::Wip => "Wip",
        }
    }
}
